//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDeliverySystem.Models.DBContext
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public short menu_food_id { get; set; }
        public short menu_restaurant_id { get; set; }
        public string menu_name { get; set; }
        [JsonIgnore]
        public virtual Food Food { get; set; }
        [JsonIgnore]
        public virtual Restaurant Restaurant { get; set; }
    }
}
